name: Azure Static Web Apps CI/CD - Prod

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_test_job:
    runs-on: ubuntu-latest
    name: Build and Test Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    needs: build_and_test_job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_RIVER_0A1C30E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"
  
  cypress_test_job:
    runs-on: ubuntu-latest
    name: Cypress Test Job
    needs: deploy_job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test
        run: | 
            npm install
            npm run cy:run -- --env url="${{ secrets.PROD_URL }}"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_RIVER_0A1C30E03 }}
          action: "close"